almost done

diff --git a/packaging/debian/DEBIAN/postinst b/packaging/debian/DEBIAN/postinst
--- a/packaging/debian/DEBIAN/postinst
+++ b/packaging/debian/DEBIAN/postinst
@@ -44,24 +44,25 @@ mkdir -p /opt/vaultier/logs/
 
 # Setup postgres account
 service postgresql start
-sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$database_user'" | grep -q 1 || \
+if sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$database_user'" &>/dev/null | grep -q 1; then
+    sudo -u postgres psql --command "ALTER USER $database_user WITH PASSWORD '$database_password';"
+    # ALTER USER Postgres WITH PASSWORD '<newpassword>';
+else
     sudo -u postgres psql --command "CREATE USER $database_user WITH SUPERUSER PASSWORD '$database_password';" &>/dev/null
-
+    #
+fi
 if ! sudo -u postgres psql ${database_name} -c '\q' &>/dev/null; then
     sudo -u postgres createdb -O ${database_user} ${database_name}
 fi
 
-
 # install Vaultier
+mkdir -p /opt/vaultier
 cd /opt/vaultier
 virtualenv venv
 
-if [ ! -f Vaultier-0.7.0.tar.gz ]; then
-    echo "nothing to install"
-fi
+/opt/vaultier/venv/bin/pip install /usr/share/vaultier/source/Vaultier-0.7.0.tar.gz
 
-/opt/vaultier/venv/bin/pip install Vaultier-0.7.0.tar.gz
-rm /opt/vaultier/Vaultier-0.7.0.tar.gz
+#rm /opt/vaultier/Vaultier-0.7.0.tar.gz
 export PYTHONPATH=/opt/vaultier/venv/lib/python2.7/site-packages/vaultier
 
 
@@ -103,14 +104,20 @@ sed -i "s/DEB_DOMAIN/${domain}/g" /etc/nginx/sites-available/vaultier
 ln -s /etc/nginx/sites-available/vaultier /etc/nginx/sites-enabled
 ln -s /etc/uwsgi/apps-available/vaultier.ini /etc/uwsgi/apps-enabled
 
-# start uwsgi
-service uwsgi start || true
 
-# start nginx
-service nginx start
+# start servers again
+if ! service uwsgi start &> /dev/null; then
+    echo "Starting uwsgi failed. Please try to start uwsgi manually."
+fi
 
-# update & run supervisor
-service supervisor start
-supervisorctl update
+if ! service nginx start &> /dev/null; then
+    echo "Starting nginx failed. Please try to start nginx manually."
+fi
+
+if ! service supervisor start &> /dev/null; then
+    echo "Starting supervisor failed. Please try to start supervisor manually."
+else
+    supervisorctl update
+fi
 
 db_stop
diff --git a/packaging/debian/DEBIAN/postrm b/packaging/debian/DEBIAN/postrm
--- a/packaging/debian/DEBIAN/postrm
+++ b/packaging/debian/DEBIAN/postrm
@@ -3,54 +3,78 @@ set -e
 
 . /usr/share/debconf/confmodule
 
-if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
-    db_get vaultier/database_name
-    echo "Found database $RET to delete"
-    database_name="$RET"
-
-    db_get vaultier/database_user
-    echo "Found user $RET to delete"
-    database_user="$RET"
-
-    if sudo -u postgres psql ${database_name} -c '\q' &>/dev/null; then
-        sudo -u postgres dropdb $database_name
-        echo "Database $database_name deleted successfully"
-    fi
-
-    sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$database_user'" | grep -q 1 && \
-        sudo -u postgres dropuser $database_user && echo "Database user $database_user deleted successfully"
-fi
-
 # Remove configuration files
+echo -n "Removing config files.. "
 rm -f /etc/supervisor/conf.d/vaultier.conf
 rm -f /etc/nginx/sites-enabled/vaultier
 rm -f /etc/nginx/sites-available/vaultier
 rm -f /etc/uwsgi/apps-enabled/vaultier.ini
 rm -f /etc/uwsgi/apps-available/vaultier.ini
+echo "OK"
 
 # Remove logs
+echo -n "Removing logs.. "
 rm -rf /opt/vaultier/logs
+echo "OK"
 
 # Remove virtualenv
+echo -n "Removing virtual environment.. "
 rm -rf /opt/vaultier/venv
+echo "OK"
 
 # Remove orphans
+echo -n "Removing orpahns.. "
 rm -f /opt/vaultier/celerybeat-schedule
 rm -f /opt/vaultier/vaultier_conf.pyc
+echo "OK"
 
+if [ "$1" = "remove" ]; then
+    echo "Purging db"
+   db_purge
+   echo "DB purged"
+fi
 
 if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
 
-    rm -rf /opt/vaultier/
-    id -f vaultier &>/dev/null && delgroup vaultier
-    id -u vaultier &>/dev/null && deluser vaultier
-    db_purge
-fi
+    database_name=$(cat /tmp/.vaultier_dbname)
+    database_user=$(cat /tmp/.vaultier_dbuser)
 
-if [ "$1" = "remove" ]; then
-   db_purge
+    if sudo -u postgres psql ${database_name} -c '\q' &>/dev/null; then
+        sudo -u postgres dropdb $database_name
+        echo "Database $database_name droped successfully"
+    else
+        echo "Removing database failed."
+    fi
+
+    sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$database_user'" | grep -q 1 && \
+        sudo -u postgres dropuser $database_user && echo "Database user $database_user deleted successfully"
+
+    rm -f /tmp/.vaultier_dbname
+    rm -f /tmp/.vaultier_dbuser
+
+    echo -n "Removing group vaultier.. "
+    id -f vaultier &>/dev/null && delgroup vaultier
+    echo "OK"
+    echo -n "Removing user vaultier.. "
+    id -u vaultier &>/dev/null && deluser vaultier
+    echo "OK"
+    db_purge
+
+    rm -f /opt/vaultier/vaultier_conf.py
+    rm -rf /opt/vaultier/
 fi
 
 # start servers again
-service uwsgi start
-service nginx start
+if ! service uwsgi start; then # &> /dev/null
+    echo "Starting uwsgi failed. Please try to start it manually."
+elsee
+    echo "Uwsgi started"
+fi
+
+if ! service nginx start; then # &> /dev/null
+    echo "Starting nginx failed. Please try to start it manually."
+else
+    echo "Nginx started"
+fi
+
+db_stop
